version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
      - echo Build started on `date`
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $DOCKER_HUB_USERNAME/$IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $DOCKER_HUB_USERNAME/$IMAGE_REPO_NAME:$IMAGE_TAG $DOCKER_HUB_USERNAME/$IMAGE_REPO_NAME:latest
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $DOCKER_HUB_USERNAME/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $DOCKER_HUB_USERNAME/$IMAGE_REPO_NAME:latest
      - echo Writing image definitions file...
      - printf '[{"name":"app","imageUri":"%s"}]' $DOCKER_HUB_USERNAME/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - '**/*'
  name: BuildArtifact

cache:
  paths:
    - '/root/.docker/**/*'